version: '2'
services:
    ec-app:
        image: ec
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ec-postgresql:5432/ec
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ec-elasticsearch:9300
        ports:
            - 8080:8080
    ec-postgresql:
        extends:
            file: postgresql.yml
            service: ec-postgresql
    ec-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ec-elasticsearch
